// app/layout.js
import { Dela_Gothic_One } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const delaGothic = Dela_Gothic_One({
  variable: "--font-dela-gothic",
  subsets: ["latin"],
  weight: "400", // único peso disponible
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${delaGothic.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
